### PR TITLE
the bone man will rise once again!

### PR DESCRIPTION
**Pull request by Dailyyy**
i love bones

### CODE REVIEW

**Comment by esirprus** [comment]
lol

**Comment by AndersDotExe** [comment]
why does this include 2000 lines of reformatting for items.xml

**Comment by Dailyyy** [comment]
because it needs to add the bone man item

**Comment by AndersDotExe** [comment]
changing indentations and removing line breaks is not part of "adding the bone man item", this is actually incomprehensible

**Comment by Dailyyy** [comment]
all i did was copy and paste an edited items.xml file which had the bone man item added to it

**Comment by AndersDotExe** [comment]
fucking where, you changed TWO THOUSAND LINES in one commit

**Comment by Dailyyy** [comment]
near osteosynthesis implants

**Comment by Mannatwo** [comment]
i'm not gonna merge a 2000 line pull request

**Pull request closed without merging**
